.PHONY: all fastalign kenlm mgiza cdec moses

all: fastalign kenlm mgiza cdec moses

fastalign:
	make -C fastalign

kenlm:
	make -C kenlm

mgiza:
	make -C mgiza

cdec:
	make -C cdec

moses:
	make -C moses
