.PHONY: all fastalign kenlm mgiza cdec

all: fastalign kenlm mgiza cdec

fastalign:
	docker build -t iems/fastalign fastalign

kenlm:
	docker build -t iems/kenlm kenlm

mgiza:
	docker build -t iems/mgiza mgiza

cdec:
	docker build -t iems/cdec cdec
