.PHONY: all fastalign kenlm mgiza cdec moses opus

all: fastalign kenlm mgiza cdec moses opus

fastalign:
	make -C fastalign

kenlm:
	make -C kenlm

mgiza:
	make -C mgiza

cdec:
	make -C cdec

moses:
	make -C moses

opus:
	make -C opus
